# Generated by Django 2.2.3 on 2019-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190723_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.TextField(max_length=500, unique=True, verbose_name='token'),
        ),
    ]
