# Generated by Django 2.2.3 on 2019-07-24 07:23

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190723_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='Userusername')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Userphone')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Userimage')),
                ('address', models.TextField(blank=True, max_length=300, null=True, verbose_name='Useraddress')),
                ('notification_status', models.BooleanField(default=False, verbose_name='Usernotification_status')),
                ('created_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Usercreate_at')),
                ('updated_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Userupdated_at')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='CustomUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=500, unique=True, verbose_name='Tokentoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser', verbose_name='Tokenuser_id')),
            ],
            options={
                'verbose_name': 'UserToken',
                'verbose_name_plural': 'UserTokens',
            },
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
