# Generated by Django 2.2.3 on 2019-07-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190724_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0, verbose_name='CustomUserscore'),
        ),
    ]
