# Generated by Django 2.2.3 on 2019-07-28 09:35

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Usercreate_at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Userupdated_at'),
        ),
    ]
