# Generated by Django 2.2.3 on 2019-08-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertoken',
            name='deviceId',
            field=models.IntegerField(choices=[(0, 'Ios'), (1, 'Android')], default=1, verbose_name='TokenDeviceId'),
        ),
        migrations.AddField(
            model_name='customusertoken',
            name='validToken',
            field=models.TextField(default='grrg', max_length=500, verbose_name='TokenValidToken'),
        ),
    ]
