# Generated by Django 2.2.3 on 2019-08-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190803_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusertoken',
            name='deviceType',
            field=models.IntegerField(choices=[(0, 'Ios'), (1, 'Android')], default=1, verbose_name='TokenDeviceType'),
        ),
        migrations.AlterField(
            model_name='customusertoken',
            name='deviceId',
            field=models.CharField(default='fwef24524tf4f', max_length=200, verbose_name='TokenDeviceId'),
        ),
        migrations.AlterField(
            model_name='customusertoken',
            name='validToken',
            field=models.TextField(max_length=500, verbose_name='TokenValidToken'),
        ),
    ]
