# Generated by Django 2.2.3 on 2019-08-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190804_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verifyCode',
            field=models.IntegerField(default=0, verbose_name='UserVerifyCode'),
        ),
        migrations.AlterField(
            model_name='customusertoken',
            name='deviceId',
            field=models.CharField(max_length=200, verbose_name='TokenDeviceId'),
        ),
        migrations.AlterField(
            model_name='customusertoken',
            name='deviceType',
            field=models.IntegerField(choices=[(0, 'Ios'), (1, 'Android')], verbose_name='TokenDeviceType'),
        ),
    ]
