# Generated by Django 2.2.3 on 2019-07-13 08:27

import cinemalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50, verbose_name='videoname')),
                ('desc', models.TextField(max_length=200, verbose_name='videodesc')),
                ('create_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='videocreatedate')),
                ('published', models.BooleanField(default=False, verbose_name='videopublished')),
                ('published_at', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='videopublishdate')),
                ('file_name', models.FileField(max_length=50, upload_to=cinemalog.models.file_location, verbose_name='videofilename')),
                ('cover_video', models.FileField(blank=True, max_length=50, null=True, upload_to=cinemalog.models.file_location, verbose_name='videocver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'permissions': (('publish_video', 'Can publish video'),),
            },
        ),
    ]
