# Generated by Django 2.2.3 on 2019-07-13 10:02

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=10, verbose_name='applicationplatform')),
                ('require_version', models.FloatField(max_length=5, verbose_name='applicationrequire')),
                ('last_version', models.FloatField(max_length=5, verbose_name='applicationlast')),
                ('generated_at', django_jalali.db.models.jDateField(verbose_name='applicationgeneratedate')),
            ],
            options={
                'verbose_name': 'ApplicationVersion',
                'verbose_name_plural': 'ApplicationVersions',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='newstitle')),
                ('desc', models.TextField(max_length=500, verbose_name='newsdesc')),
                ('image', models.URLField(null=True, verbose_name='newsimage')),
                ('source', models.URLField(null=True, verbose_name='newssource')),
                ('published_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='newspublished')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='SendAdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='sendadvtitle')),
                ('content', models.TextField(max_length=200, verbose_name='sendadvcontent')),
                ('adv_type', models.CharField(choices=[('معرفی اپلیکیشن', 'معرفی اپلیکیشن'), ('معرفی بازی', 'معرفی بازی')], max_length=30, verbose_name='sendadvtype')),
                ('link', models.URLField(verbose_name='sendadvlink')),
                ('pic', models.FileField(max_length=30, upload_to='', verbose_name='sendadvpic')),
                ('platform_android', models.BooleanField(default=False, verbose_name='sendadvandroid')),
                ('platform_ios', models.BooleanField(default=False, verbose_name='sendadvios')),
            ],
            options={
                'verbose_name': 'SendAdv',
                'verbose_name_plural': 'SendAdv',
            },
        ),
        migrations.CreateModel(
            name='SendPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='sendpushtitle')),
                ('content', models.TextField(max_length=200, verbose_name='sendpushcontent')),
                ('platform_android', models.BooleanField(default=False, verbose_name='sendpushandroid')),
                ('platform_ios', models.BooleanField(default=False, verbose_name='sendpushios')),
            ],
            options={
                'verbose_name': 'SendPush',
                'verbose_name_plural': 'SendPushs',
            },
        ),
    ]
