# Generated by Django 2.2.3 on 2019-07-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0006_applicationversion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
    ]
