# Generated by Django 2.2.3 on 2019-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0007_auto_20190715_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationversion',
            old_name='require_version',
            new_name='required_version',
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='platform',
            field=models.CharField(choices=[(1, 'Android'), (2, 'IOS')], max_length=10, verbose_name='نوع سیستم'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='adv_type',
            field=models.CharField(choices=[('introduce app', 'معرفی اپلیکیشن'), ('introduce game', 'معرفی بازی')], max_length=30, verbose_name='نوع تبلیغ'),
        ),
    ]
