# Generated by Django 2.2.3 on 2019-07-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0009_auto_20190721_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0, verbose_name='view'),
        ),
    ]
