# Generated by Django 2.2.3 on 2019-07-23 12:28

import cinemalog.models
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0010_video_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationversion',
            options={'verbose_name': 'ApplicationVersion', 'verbose_name_plural': 'ApplicationVersions'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='sendadv',
            options={'verbose_name': 'SendAdv', 'verbose_name_plural': 'SendAdv'},
        ),
        migrations.AlterModelOptions(
            name='sendpush',
            options={'verbose_name': 'SendPush', 'verbose_name_plural': 'SendPushs'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'permissions': (('publish_video', 'Can publish video'),), 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='generated_at',
            field=django_jalali.db.models.jDateField(verbose_name='applicationgeneratedate'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='last_version',
            field=models.FloatField(max_length=5, verbose_name='applicationlast'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Android'), (2, 'IOS')], verbose_name='applicationplatform'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='required_version',
            field=models.FloatField(max_length=5, verbose_name='applicationrequire'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='create_at',
            field=django_jalali.db.models.jDateField(verbose_name='competitioncreatedate'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=50, verbose_name='competitiontitle'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='deliverDate',
            field=django_jalali.db.models.jDateField(verbose_name='giftdeliverdate'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='giftdesc'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='pic',
            field=models.FileField(null=True, upload_to='', verbose_name='giftpic'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(max_length=30, verbose_name='gifttitle'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(max_length=500, verbose_name='newsdesc'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(null=True, verbose_name='newsimage'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='newspublished'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.URLField(null=True, verbose_name='newssource'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='newstitle'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=30, verbose_name='questionanswer1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=30, verbose_name='questionanswer2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=30, verbose_name='questionanswer3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(max_length=30, verbose_name='questionanswer4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=30, verbose_name='questioncorrect'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=100, verbose_name='questionuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_ca',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='questionscore_ca'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_wa',
            field=models.IntegerField(choices=[(-1, -1), (-2, -2), (-3, -3), (-4, -4), (-5, -5)], null=True, verbose_name='questionscore_wa'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='adv_type',
            field=models.CharField(choices=[('introduce app', 'معرفی اپلیکیشن'), ('introduce game', 'معرفی بازی')], max_length=30, verbose_name='sendadvtype'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='content',
            field=models.TextField(max_length=200, verbose_name='sendadvcontent'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='link',
            field=models.URLField(verbose_name='sendadvlink'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='pic',
            field=models.FileField(max_length=30, upload_to='', verbose_name='sendadvpic'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='platform_android',
            field=models.BooleanField(default=False, verbose_name='sendadvandroid'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='platform_ios',
            field=models.BooleanField(default=False, verbose_name='sendadvios'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='title',
            field=models.CharField(max_length=30, verbose_name='sendadvtitle'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='content',
            field=models.TextField(max_length=200, verbose_name='sendpushcontent'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='platform_android',
            field=models.BooleanField(default=False, verbose_name='sendpushandroid'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='platform_ios',
            field=models.BooleanField(default=False, verbose_name='sendpushios'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='title',
            field=models.CharField(max_length=30, verbose_name='sendpushtitle'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_video',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=cinemalog.models.file_location, verbose_name='videocver'),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='videocreatedate'),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='videodesc'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.FileField(max_length=50, upload_to=cinemalog.models.file_location, verbose_name='videofilename'),
        ),
        migrations.AlterField(
            model_name='video',
            name='film_name',
            field=models.CharField(max_length=50, verbose_name='videoname'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False, verbose_name='videopublished'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='videopublishdate'),
        ),
    ]
