# Generated by Django 2.2.3 on 2019-07-24 07:23

import cinemalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190724_1153'),
        ('cinemalog', '0011_auto_20190723_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationversion',
            options={'verbose_name': 'نسخه اپلیکیشن', 'verbose_name_plural': 'نسخه اپلیکیشن'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'مسابقه', 'verbose_name_plural': 'مسابقات'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'اخبار', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='sendadv',
            options={'verbose_name': 'ارسال تبلیغات', 'verbose_name_plural': 'ارسال تبلیغات'},
        ),
        migrations.AlterModelOptions(
            name='sendpush',
            options={'verbose_name': 'ارسال نوتیفیکیشن', 'verbose_name_plural': 'ارسال نوتیفیکیشن'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'permissions': (('publish_video', 'Can publish video'),), 'verbose_name': 'دیالوگ', 'verbose_name_plural': 'دیالوگ ها'},
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='generated_at',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ به روز رسانی'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='last_version',
            field=models.FloatField(max_length=5, verbose_name='آخرین نسخه'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Android'), (2, 'IOS')], verbose_name='نوع سیستم'),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='required_version',
            field=models.FloatField(max_length=5, verbose_name='نسخه حداقل'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='create_at',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ایجاد مسابقه'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان مسابقه'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='deliverDate',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ اهدای جایزه'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='متن توضیحات جایزه'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='pic',
            field=models.FileField(null=True, upload_to='', verbose_name='عکس جایزه'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان جایزه'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(max_length=500, verbose_name='مشروح خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(null=True, verbose_name='عکس مربوط به خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ انتشار خبر'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.URLField(null=True, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان خبر'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=30, verbose_name='جواب اول'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=30, verbose_name='جواب دوم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=30, verbose_name='جواب سوم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(max_length=30, verbose_name='جواب چهارم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=30, verbose_name='جواب صحیح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=100, verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_ca',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name=' امتیاز پاسخ صحیح'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score_wa',
            field=models.IntegerField(choices=[(-1, -1), (-2, -2), (-3, -3), (-4, -4), (-5, -5)], null=True, verbose_name=' امتیاز پاسخ غلط'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='adv_type',
            field=models.CharField(choices=[('introduce app', 'معرفی اپلیکیشن'), ('introduce game', 'معرفی بازی')], max_length=30, verbose_name='نوع تبلیغ'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='content',
            field=models.TextField(max_length=200, verbose_name='متن پوش'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='link',
            field=models.URLField(verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='pic',
            field=models.FileField(max_length=30, upload_to='', verbose_name='آپلود عکس'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='platform_android',
            field=models.BooleanField(default=False, verbose_name='اندروید'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='platform_ios',
            field=models.BooleanField(default=False, verbose_name='آی او اس'),
        ),
        migrations.AlterField(
            model_name='sendadv',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='content',
            field=models.TextField(max_length=200, verbose_name='متن پوش'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='platform_android',
            field=models.BooleanField(default=False, verbose_name='اندروید'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='platform_ios',
            field=models.BooleanField(default=False, verbose_name='آی او اس'),
        ),
        migrations.AlterField(
            model_name='sendpush',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cover_video',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=cinemalog.models.file_location, verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AlterField(
            model_name='video',
            name='create_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد دیالوگ'),
        ),
        migrations.AlterField(
            model_name='video',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='یک دیالوگ از فیلم'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.FileField(max_length=50, upload_to=cinemalog.models.file_location, verbose_name='ویدیو فیلم'),
        ),
        migrations.AlterField(
            model_name='video',
            name='film_name',
            field=models.CharField(max_length=50, verbose_name='نام فیلم'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False, verbose_name='انتشار ویدیو'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Videouser_id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Videoview'),
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewAt', django_jalali.db.models.jDateField(verbose_name='VideoViewveiwAt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser', verbose_name='user_id')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemalog.Video', verbose_name='video_id')),
            ],
            options={
                'verbose_name': 'Video user view',
                'verbose_name_plural': 'Video user views',
            },
        ),
    ]
