# Generated by Django 2.2.3 on 2019-07-24 09:33

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190724_1153'),
        ('cinemalog', '0012_auto_20190724_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewAt', django_jalali.db.models.jDateField(verbose_name='NewsViewveiwAt')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemalog.News', verbose_name='news_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'News user view',
                'verbose_name_plural': 'News user views',
            },
        ),
    ]
