# Generated by Django 2.2.3 on 2019-07-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0013_newsview'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Newsview'),
        ),
    ]
