# Generated by Django 2.2.3 on 2019-07-24 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemalog', '0014_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='create_at',
        ),
        migrations.AddField(
            model_name='competition',
            name='created_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='competitioncreatedat'),
        ),
        migrations.AddField(
            model_name='competition',
            name='deleted_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='competitiondeletedat'),
        ),
        migrations.AddField(
            model_name='competition',
            name='release',
            field=models.BooleanField(default=False, verbose_name='competitonrelease'),
        ),
        migrations.AddField(
            model_name='competition',
            name='release_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='competitionreleasedate'),
        ),
        migrations.AddField(
            model_name='competition',
            name='updated_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='competitionupdatedat'),
        ),
        migrations.AddField(
            model_name='competition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
