# Generated by Django 2.2.3 on 2019-07-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0018_auto_20190727_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
