# Generated by Django 2.2.3 on 2019-07-27 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0020_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Competition',
            new_name='competition',
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
    ]
