# Generated by Django 2.2.3 on 2019-07-27 07:07

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0021_auto_20190727_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Questioncreatedat'),
        ),
    ]
