# Generated by Django 2.2.3 on 2019-07-27 08:32

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190724_1153'),
        ('cinemalog', '0022_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=django_jalali.db.models.jDateField(verbose_name='Questioncreatedat'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50, verbose_name='Answeranswer')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemalog.Competition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemalog.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'UserAnswer',
                'verbose_name_plural': 'UserAnswers',
            },
        ),
    ]
