# Generated by Django 2.2.3 on 2019-08-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190814_0951'),
        ('cinemalog', '0023_auto_20190727_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='plantitle')),
                ('typee', models.IntegerField(verbose_name='plantype')),
                ('days', models.IntegerField(verbose_name='plandays')),
                ('price', models.CharField(max_length=10, verbose_name='planprice')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'UserAnswer', 'verbose_name_plural': 'جواب کاربران'},
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_at', models.DateTimeField(verbose_name='userplanbuyat')),
                ('expire_at', models.DateTimeField(verbose_name='userplanexpireat')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemalog.Plan', verbose_name='planId')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser', verbose_name='userId')),
            ],
            options={
                'verbose_name': 'User Plan',
                'verbose_name_plural': 'User Plans',
            },
        ),
    ]
