# Generated by Django 2.2.3 on 2019-08-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemalog', '0024_auto_20190814_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Expire')], default=0, verbose_name='userplanstatus'),
        ),
    ]
